@startuml [practice]
[*] --> 未認証 : システム起動
未認証:entry/ログイン画面表示
未認証 --> 未認証 : ログイン失敗
未認証 --> 認証済み : ログイン成功
未認証 --> [*] : 終了ボタン押下
認証済み --> [*] : エラー発生
認証済み:entry/勤怠入力画面表示
認証済み:出社ボタン押下/出社処理
認証済み:退勤ボタン押下/退勤処理
@enduml