@startuml [test]
title ビデオ状態遷移図のサンプル
[*] --> 停止中
停止中 : entry / 停止する
停止中 --> 稼働中 : 再生ボタンが押された
稼働中 : do / 再生する
稼働中 --> 停止中 : 再生ボタンが押された
稼働中 --> 早送り : 早送りボタンが押された
早送り : do / 早送りする
早送り --> 稼働中 : 早送りボタンが離された
稼働中 --> 早戻し : 早戻しボタンが押された
早戻し : do / 早戻しする
早戻し --> 稼働中 : 早戻しボタンが離された
稼働中 --> 一時停止中 : 再生ボタンが押された
一時停止中 : entry / 早戻しする
一時停止中 --> 稼働中 : 再生ボタンが押された
@enduml